// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbhwpJ2BGxprtyqBe97PO5dz5hbat5SZY',
    appId: '1:151585050951:web:ea49fee39615fd12d93c62',
    messagingSenderId: '151585050951',
    projectId: 'ecommerce-0101-46c9a',
    authDomain: 'ecommerce-0101-46c9a.firebaseapp.com',
    storageBucket: 'ecommerce-0101-46c9a.firebasestorage.app',
    measurementId: 'G-TJ54JNSL4G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI2EpZI1XeSLlHVDmwn4cuTuIGpBvFKtE',
    appId: '1:151585050951:android:58b1bb0de9dc9f91d93c62',
    messagingSenderId: '151585050951',
    projectId: 'ecommerce-0101-46c9a',
    storageBucket: 'ecommerce-0101-46c9a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN03HuAzbYzMJTAeEatDqUWEQFIohKH38',
    appId: '1:151585050951:ios:013e6a4ffe2db25fd93c62',
    messagingSenderId: '151585050951',
    projectId: 'ecommerce-0101-46c9a',
    storageBucket: 'ecommerce-0101-46c9a.firebasestorage.app',
    iosBundleId: 'com.example.mainEcommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN03HuAzbYzMJTAeEatDqUWEQFIohKH38',
    appId: '1:151585050951:ios:013e6a4ffe2db25fd93c62',
    messagingSenderId: '151585050951',
    projectId: 'ecommerce-0101-46c9a',
    storageBucket: 'ecommerce-0101-46c9a.firebasestorage.app',
    iosBundleId: 'com.example.mainEcommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbhwpJ2BGxprtyqBe97PO5dz5hbat5SZY',
    appId: '1:151585050951:web:32cd82d388f958b1d93c62',
    messagingSenderId: '151585050951',
    projectId: 'ecommerce-0101-46c9a',
    authDomain: 'ecommerce-0101-46c9a.firebaseapp.com',
    storageBucket: 'ecommerce-0101-46c9a.firebasestorage.app',
    measurementId: 'G-LDPF5VXQNB',
  );
}
